from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional
from uuid import uuid4


@dataclass
class DocumentationChunk:
    """
    Represents a segment of text extracted from documentation with associated metadata for retrieval.
    """
    id: str
    content: str
    source_url: str
    title: str
    created_at: datetime
    updated_at: datetime
    metadata: Dict[str, str]

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid4())
        if not self.created_at:
            self.created_at = datetime.now()
        if not self.updated_at:
            self.updated_at = datetime.now()


@dataclass
class EmbeddingVector:
    """
    Numerical representation of text content generated by Cohere models, stored in Qdrant for similarity search.
    """
    id: str
    vector: List[float]
    chunk_id: str
    model_version: str

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid4())


@dataclass
class SourceMetadata:
    """
    Information about the original documentation page including URL, title, and any relevant contextual data.
    """
    source_url: str
    title: str
    last_crawled: datetime
    status: str
    checksum: str

    def __post_init__(self):
        if not self.last_crawled:
            self.last_crawled = datetime.now()